<!DOCTYPE html>

<html lang="es">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="google-site-verification" content="L-dT_n3G3pnUthuG06qm1BNTxGwUCzOwI8XXf8YjAsQ" />

  <title>Account<title>


  <link rel='icon' type='image/x-icon' href='//static.avast.com/my-account/my/my-account-css/1.0.71/favicons/favicon-avast.ico'>
  <link rel='stylesheet' href='//static.avast.com/my-account/my/my-account-js-css/2.0.35/font-avast.css'>
  <link rel='stylesheet' href='//static.avast.com/my-account/my/my-account-js-css/2.0.35/main-avast.css'>
  <link rel='stylesheet' href='//static.avast.com/my-account/my/my-account-js-css/2.0.35/flags.css'>

  <script type="module" crossorigin src="//static.avast.com/my-account/my/my-account-js-account/2.0.86/account.js"></script>
  <link rel="modulepreload" href="//static.avast.com/my-account/my/my-account-js-account/2.0.86/vendor.js">
  <link rel="stylesheet" href="//static.avast.com/my-account/my/my-account-js-account/2.0.86/account.css">

  <-- Optimize Page Hiding Snippet -->
	<style>.async-hide { opacity: 0 !important} <style>
	<script>(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
	h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};
	(a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;
	})(window,document.documentElement,'async-hide','dataLayer',2000,
	{'GTM-PZ48F8':true});<script>
	-- end Optimize Page Hiding Snippet -->

	-- Google Tag Manager -->
	<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','GTM-PZ48F8');</script>
	<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Cache-control" content="no-cache, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <meta name="description" content="Bitdefender Account" />

    <link rel="icon" href="/favicon.ico" >
    <title>Bitdefender Account<title>

    <script type="text/javascript">
var BUILD_VERSION = '1.1.218'
    <script>
    <script
        type="text/javascript"
        id="Cookiebot" 
        src="https://consent.cookiebot.com/uc.js" 
        data-cbid="b9f10771-8285-4ce4-af1c-a17f5d8e57f2" 
        async>
    <script>
    <script 
        type="text/javascript" 
        src="/static/js/config.js?v=1.1.218">
    <script>
    <script type="text/javascript">
        var s = document.createElement('script');
        s.src = window.OMNITURE_PATH;
        s.type = "text/javascript";
        document.getElementsByTagName('head')[0].appendChild(s);
    <script>
    <script type="text/javascript">
        window.addEventListener("CookiebotOnConsentReady", (event) => {
            if (window['Cookiebot'] && window['adobe']) {
                try {
                    var consent = window['Cookiebot'].consent;
                    if (consent.marketing && consent.statistics) {
                        window['adobe'].optIn.approveAll();
                    } else { 
                        if (!consent.marketing && !consent.statistics) {
                            window['adobe'].optIn.denyAll();
                        } else if (!consent.marketing) {
                            window['adobe'].optIn.approve([window['adobe'].OptInCategories.ANALYTICS, window['adobe'].OptInCategories.ECID], true);
                            window['adobe'].optIn.deny([window['adobe'].OptInCategories.AAM, window['adobe'].OptInCategories.TARGET], true);
                        } else {
                            window['adobe'].optIn.approve([window['adobe'].OptInCategories.AAM, window['adobe'].OptInCategories.TARGET, window['adobe'].OptInCategories.ECID], true)
                            window['adobe'].optIn.deny([window['adobe'].OptInCategories.ANALYTICS], true);
                        }
                    }
                    window['adobe'].optIn.complete();
                } catch (err) {
                    console.log('Cookie consent error!');
                }
            }
        });
    <script>
  <script type="module" crossorigin src="/static/js/index.4944af93.js"></script>
  <link rel="modulepreload" crossorigin href="/static/js/_commonjsHelpers.725317a4.js">
  <link rel="modulepreload" crossorigin href="/static/js/dayjs.min.9026c0f9.js">
  <link rel="stylesheet" href="/static/css/index.375476b8.css">
  <script type="module">import.meta.url;import("_").catch(()=>1);async function* g(){};window.__vite_is_modern_browser=true;<script>
  <script type="module">!function(){if(window.__vite_is_modern_browser)return;console.warn("vite: loading legacy chunks, syntax error above and the same error below should be ignored");var e=document.getElementById("vite-legacy-polyfill"),n=document.createElement("script");n.src=e.src,n.onload=function(){System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))},document.body.appendChild(n)}();<script>
<head>
<body class="alc-on">
    <div id="app"><div>
    <div id="alc"><div>

    
    
    -- built files will be auto injected -->
  <script nomodule>function(){var e=document,t=e.createElement("script");if(("noModule"in t)&&"onbeforeload"in t){var n=1;e.addEventListener("beforeload",(function(e){if(e.target===t)n=0;else if(e.target.hasAttribute("nomodule")||n)return;e.preventDefault()}),!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}<script>
  <script nomodule crossorigin id="vite-legacy-polyfill" src="/static/js/polyfills-legacy.7bc0fdba.js"><script>
  <script nomodule crossorigin id="vite-legacy-entry" data-src="/static/js/index-legacy.a6370eeb.js">System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))<script>
<body>
<html>
<--  Google Tag Manager -->

<head>

<body class="avast">


	-- Google Tag Manager (noscript) --
	<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PZ48F8"
	height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
	-- Google Tag Manager (noscript) --

<div id="account" class="app"><div>

<script>

  var __SITE_CONFIG__ = {
    familyEnabled: false,
    devicesEnabled: false,
    licenses: {
      hasLicenses: true,
    },
  }

  var __APPCONFIG__ = {
    LOCALE: 'es-mx',
    BRAND: 'avast',
    SITE_KEY: '6LeIoPEcAAAAAOcvGRHpSsT0LVpcOkUZAEIbPqIA',
    ENVIRONMENT: 'production',
    APPLICATION: 'account',

  };
  var __ACCOUNT__ = {
    UUID: '3t1peqAlRoPzYZOW',
    FIRST_NAME: 'Fernando Guadalupe',
    LAST_NAME: 'mendez ESPINOZA',
    HAS_PASSWORD: true,
    PRIMARY_EMAIL: 'alaikum226@gmail.com',
    OTHER_VERIFIED_EMAILS: [
      'fm8252025@gmail.com', 'leondante007@gmail.com', 'salamealeikum869@gmail.com'
    ],
    UNVERIFIED_EMAILS: [
      
    ],
    TFA_METHODS: [
      
    ]
  };
<script>

<body>
<html>
