 safebrowsing.googleapis.com
    ----------------------------------------
    Nombre de registro  . : safebrowsing.googleapis.com
    Tipo de registro  . . : 1
    Período de vida . . . : 66
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 142.250.69.10


    0.pool.ntp.org
    ----------------------------------------
    Nombre de registro  . : 0.pool.ntp.org
    Tipo de registro  . . : 1
    Período de vida . . . : 21
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 193.182.111.13


    Nombre de registro  . : 0.pool.ntp.org
    Tipo de registro  . . : 1
    Período de vida . . . : 21
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 162.159.200.123


    Nombre de registro  . : 0.pool.ntp.org
    Tipo de registro  . . : 1
    Período de vida . . . : 21
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 192.36.143.130


    Nombre de registro  . : 0.pool.ntp.org
    Tipo de registro  . . : 1
    Período de vida . . . : 21
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 162.159.200.1


    gcp.nos.avast.com
    ----------------------------------------
    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 148
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.74.27.206


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 148
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.140.0.47


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 148
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.159.84.40


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 148
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.75.10.118


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 148
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 35.205.49.198


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 148
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 35.205.128.73


    2.pool.ntp.org
    ----------------------------------------
    Nombre de registro  . : 2.pool.ntp.org
    Tipo de registro  . . : 1
    Período de vida . . . : 101
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 192.36.143.130


    Nombre de registro  . : 2.pool.ntp.org
    Tipo de registro  . . : 1
    Período de vida . . . : 101
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 162.159.200.123


    Nombre de registro  . : 2.pool.ntp.org
    Tipo de registro  . . : 1
    Período de vida . . . : 101
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 45.231.168.6


    Nombre de registro  . : 2.pool.ntp.org
    Tipo de registro  . . : 1
    Período de vida . . . : 101
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 162.159.200.1


    example.org
    ----------------------------------------
    Nombre de registro  . : example.org
    Tipo de registro  . . : 28
    Período de vida . . . : 24962
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2606:2800:220:1:248:1893:25c8:1946


    example.org
    ----------------------------------------
    Nombre de registro  . : example.org
    Tipo de registro  . . : 1
    Período de vida . . . : 23902
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 93.184.216.34


    a1887.dscq.akamai.net
    ----------------------------------------
    Nombre de registro  . : a1887.dscq.akamai.net
    Tipo de registro  . . : 1
    Período de vida . . . : 16
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 104.124.0.8


    Nombre de registro  . : a1887.dscq.akamai.net
    Tipo de registro  . . : 1
    Período de vida . . . : 16
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 23.193.172.216


    incoming.telemetry.mozilla.org
    ----------------------------------------
    Nombre de registro  . : incoming.telemetry.mozilla.org
    Tipo de registro  . . : 5
    Período de vida . . . : 31
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : telemetry-incoming.r53-2.services.mozilla.com


    Nombre de registro  . : telemetry-incoming.r53-2.services.mozilla.com
    Tipo de registro  . . : 5
    Período de vida . . . : 31
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : prod.ingestion-edge.prod.dataops.mozgcp.net


    Nombre de registro  . : prod.ingestion-edge.prod.dataops.mozgcp.net
    Tipo de registro  . . : 1
    Período de vida . . . : 31
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.120.208.123


    client.wns.windows.com
    ----------------------------------------
    Nombre de registro  . : client.wns.windows.com
    Tipo de registro  . . : 5
    Período de vida . . . : 30
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : wns.notify.trafficmanager.net


    Nombre de registro  . : wns.notify.trafficmanager.net
    Tipo de registro  . . : 1
    Período de vida . . . : 30
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 20.7.1.246


    b.8.e.b.5.5.e.f.f.f.2.0.4.a.6.c.a.d.8.2.e.1.0.0.e.3.0.1.6.0.8.2.ip6.arpa
    ----------------------------------------
    Nombre de registro  . : b.8.e.b.5.5.e.f.f.f.2.0.4.a.6.c.a.d.8.2.e.1.0.0.e.3.0.1.6.0.8.2.ip6.arpa
    Tipo de registro  . . : 12
    Período de vida . . . : 81719
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro PTR. . . . . : 2806-103e-001e-28da-c6a4-02ff-fe55-be8b.ipv6.infinitum.net.mx


    activity.windows.com
    ----------------------------------------
    Nombre de registro  . : activity.windows.com
    Tipo de registro  . . : 5
    Período de vida . . . : 15
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : activity-geo.trafficmanager.net


    Nombre de registro  . : activity-geo.trafficmanager.net
    Tipo de registro  . . : 1
    Período de vida . . . : 15
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 20.69.137.228


    push.services.mozilla.com
    ----------------------------------------
    Nombre de registro  . : push.services.mozilla.com
    Tipo de registro  . . : 5
    Período de vida . . . : 5
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : autopush.prod.mozaws.net


    Nombre de registro  . : autopush.prod.mozaws.net
    Tipo de registro  . . : 1
    Período de vida . . . : 5
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 35.163.38.240


    Nombre de registro  . : autopush.prod.mozaws.net
    Tipo de registro  . . : 1
    Período de vida . . . : 5
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 54.149.149.164


    Nombre de registro  . : autopush.prod.mozaws.net
    Tipo de registro  . . : 1
    Período de vida . . . : 5
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 35.160.122.190


    Nombre de registro  . : autopush.prod.mozaws.net
    Tipo de registro  . . : 1
    Período de vida . . . : 5
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 44.228.230.125


    Nombre de registro  . : autopush.prod.mozaws.net
    Tipo de registro  . . : 1
    Período de vida . . . : 5
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 54.148.231.253


    Nombre de registro  . : autopush.prod.mozaws.net
    Tipo de registro  . . : 1
    Período de vida . . . : 5
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 54.187.102.159


    Nombre de registro  . : autopush.prod.mozaws.net
    Tipo de registro  . . : 1
    Período de vida . . . : 5
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 44.238.73.182


    Nombre de registro  . : autopush.prod.mozaws.net
    Tipo de registro  . . : 1
    Período de vida . . . : 5
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 35.163.117.112


    content-signature-2.cdn.mozilla.net
    ----------------------------------------
    Nombre de registro  . : content-signature-2.cdn.mozilla.net
    Tipo de registro  . . : 5
    Período de vida . . . : 265
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : content-signature-chains.prod.autograph.services.mozaws.net


    Nombre de registro  . : content-signature-chains.prod.autograph.services.mozaws.net
    Tipo de registro  . . : 5
    Período de vida . . . : 265
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : prod.content-signature-chains.prod.webservices.mozgcp.net


    Nombre de registro  . : prod.content-signature-chains.prod.webservices.mozgcp.net
    Tipo de registro  . . : 28
    Período de vida . . . : 265
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2600:1901:0:92a9::


    content-signature-2.cdn.mozilla.net
    ----------------------------------------
    Nombre de registro  . : content-signature-2.cdn.mozilla.net
    Tipo de registro  . . : 5
    Período de vida . . . : 207
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : content-signature-chains.prod.autograph.services.mozaws.net


    Nombre de registro  . : content-signature-chains.prod.autograph.services.mozaws.net
    Tipo de registro  . . : 5
    Período de vida . . . : 207
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : prod.content-signature-chains.prod.webservices.mozgcp.net


    Nombre de registro  . : prod.content-signature-chains.prod.webservices.mozgcp.net
    Tipo de registro  . . : 1
    Período de vida . . . : 207
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.160.144.191


    prod.balrog.prod.cloudops.mozgcp.net
    ----------------------------------------
    Nombre de registro  . : prod.balrog.prod.cloudops.mozgcp.net
    Tipo de registro  . . : 1
    Período de vida . . . : 19
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 35.244.181.201


    ipv4only.arpa
    ----------------------------------------
    Nombre de registro  . : ipv4only.arpa
    Tipo de registro  . . : 1
    Período de vida . . . : 23899
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 192.0.0.170


    Nombre de registro  . : ipv4only.arpa
    Tipo de registro  . . : 1
    Período de vida . . . : 23899
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 192.0.0.171


    prod.ingestion-edge.prod.dataops.mozgcp.net
    ----------------------------------------
    Nombre de registro  . : prod.ingestion-edge.prod.dataops.mozgcp.net
    Tipo de registro  . . : 1
    Período de vida . . . : 27
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.120.208.123


    firefox.settings.services.mozilla.com
    ----------------------------------------
    Nombre de registro  . : firefox.settings.services.mozilla.com
    Tipo de registro  . . : 1
    Período de vida . . . : 19
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 35.241.9.150


    spclient.wg.spotify.com
    ----------------------------------------
    Nombre de registro  . : spclient.wg.spotify.com
    Tipo de registro  . . : 5
    Período de vida . . . : 34
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : edge-web.dual-gslb.spotify.com


    Nombre de registro  . : edge-web.dual-gslb.spotify.com
    Tipo de registro  . . : 28
    Período de vida . . . : 34
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2600:1901:1:c36::


    spclient.wg.spotify.com
    ----------------------------------------
    Nombre de registro  . : spclient.wg.spotify.com
    Tipo de registro  . . : 5
    Período de vida . . . : 4
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : edge-web.dual-gslb.spotify.com


    Nombre de registro  . : edge-web.dual-gslb.spotify.com
    Tipo de registro  . . : 1
    Período de vida . . . : 4
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 35.186.224.25


    sync-1-us-west1-g.sync.services.mozilla.com
    ----------------------------------------
    Nombre de registro  . : sync-1-us-west1-g.sync.services.mozilla.com
    Tipo de registro  . . : 1
    Período de vida . . . : 821
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 35.186.227.140


    detectportal.firefox.com
    ----------------------------------------
    Nombre de registro  . : detectportal.firefox.com
    Tipo de registro  . . : 5
    Período de vida . . . : 7
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : detectportal.prod.mozaws.net


    Nombre de registro  . : detectportal.prod.mozaws.net
    Tipo de registro  . . : 5
    Período de vida . . . : 7
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : prod.detectportal.prod.cloudops.mozgcp.net


    Nombre de registro  . : prod.detectportal.prod.cloudops.mozgcp.net
    Tipo de registro  . . : 1
    Período de vida . . . : 7
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.107.221.82


    detectportal.firefox.com
    ----------------------------------------
    Nombre de registro  . : detectportal.firefox.com
    Tipo de registro  . . : 5
    Período de vida . . . : 7
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : detectportal.prod.mozaws.net


    Nombre de registro  . : detectportal.prod.mozaws.net
    Tipo de registro  . . : 5
    Período de vida . . . : 7
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : prod.detectportal.prod.cloudops.mozgcp.net


    Nombre de registro  . : prod.detectportal.prod.cloudops.mozgcp.net
    Tipo de registro  . . : 1
    Período de vida . . . : 7
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.107.221.82


    s-nuistatic.avcdn.net
    ----------------------------------------
    Nombre de registro  . : s-nuistatic.avcdn.net
    Tipo de registro  . . : 5
    Período de vida . . . : 1
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : s-nuistatic.avcdn.net.edgekey.net


    Nombre de registro  . : s-nuistatic.avcdn.net.edgekey.net
    Tipo de registro  . . : 5
    Período de vida . . . : 1
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : e9229.dscd.akamaiedge.net


    Nombre de registro  . : e9229.dscd.akamaiedge.net
    Tipo de registro  . . : 28
    Período de vida . . . : 1
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2600:141c:6800:682::240d


    Nombre de registro  . : e9229.dscd.akamaiedge.net
    Tipo de registro  . . : 28
    Período de vida . . . : 1
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2600:141c:6800:68e::240d


    ip-info.ff.avast.com
    ----------------------------------------
    Nombre de registro  . : ip-info.ff.avast.com
    Tipo de registro  . . : 5
    Período de vida . . . : 44
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : ip-info-gcp.ff.avast.com


    Nombre de registro  . : ip-info-gcp.ff.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 44
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.149.149.62


    1.pool.ntp.org
    ----------------------------------------
    Nombre de registro  . : 1.pool.ntp.org
    Tipo de registro  . . : 1
    Período de vida . . . : 17
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 192.36.143.130


    Nombre de registro  . : 1.pool.ntp.org
    Tipo de registro  . . : 1
    Período de vida . . . : 17
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 193.182.111.13


    Nombre de registro  . : 1.pool.ntp.org
    Tipo de registro  . . : 1
    Período de vida . . . : 17
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 162.159.200.1


    Nombre de registro  . : 1.pool.ntp.org
    Tipo de registro  . . : 1
    Período de vida . . . : 17
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 45.231.168.6


    prod.tokenserver.prod.cloudops.mozgcp.net
    ----------------------------------------
    Nombre de registro  . : prod.tokenserver.prod.cloudops.mozgcp.net
    Tipo de registro  . . : 1
    Período de vida . . . : 342
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.107.141.31


    api.msn.com
    ----------------------------------------
    Nombre de registro  . : api.msn.com
    Tipo de registro  . . : 5
    Período de vida . . . : 125
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : api-msn-com.a-0003.a-msedge.net


    Nombre de registro  . : api-msn-com.a-0003.a-msedge.net
    Tipo de registro  . . : 5
    Período de vida . . . : 125
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : a-0003.a-msedge.net


    Nombre de registro  . : a-0003.a-msedge.net
    Tipo de registro  . . : 1
    Período de vida . . . : 125
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 204.79.197.203


    _nos._tcp.nos.avast.com
    ----------------------------------------
    Nombre de registro  . : _nos._tcp.nos.avast.com
    Tipo de registro  . . : 33
    Período de vida . . . : 127
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro SRV. . . . . : gcp.nos.avast.com
                            50
                            80
                            443


    Nombre de registro  . : _nos._tcp.nos.avast.com
    Tipo de registro  . . : 33
    Período de vida . . . : 127
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro SRV. . . . . : gcp.nos.avast.com
                            50
                            80
                            7500


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 127
    Longitud de datos . . : 4
    Sección . . . . . . . : adicional
    Un registro (host). . : 34.74.27.206


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 127
    Longitud de datos . . : 4
    Sección . . . . . . . : adicional
    Un registro (host). . : 34.79.222.182


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 127
    Longitud de datos . . : 4
    Sección . . . . . . . : adicional
    Un registro (host). . : 34.159.37.72


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 127
    Longitud de datos . . : 4
    Sección . . . . . . . : adicional
    Un registro (host). . : 35.231.83.144


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 127
    Longitud de datos . . : 4
    Sección . . . . . . . : adicional
    Un registro (host). . : 34.83.124.54


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 127
    Longitud de datos . . : 4
    Sección . . . . . . . : adicional
    Un registro (host). . : 34.159.84.40


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 127
    Longitud de datos . . : 4
    Sección . . . . . . . : adicional
    Un registro (host). . : 34.74.27.206


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 127
    Longitud de datos . . : 4
    Sección . . . . . . . : adicional
    Un registro (host). . : 34.79.222.182


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 127
    Longitud de datos . . : 4
    Sección . . . . . . . : adicional
    Un registro (host). . : 34.159.37.72


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 127
    Longitud de datos . . : 4
    Sección . . . . . . . : adicional
    Un registro (host). . : 35.231.83.144


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 127
    Longitud de datos . . : 4
    Sección . . . . . . . : adicional
    Un registro (host). . : 34.83.124.54


    Nombre de registro  . : gcp.nos.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 127
    Longitud de datos . . : 4
    Sección . . . . . . . : adicional
    Un registro (host). . : 34.159.84.40


    firefoxusercontent.com
    ----------------------------------------
    Nombre de registro  . : firefoxusercontent.com
    Tipo de registro  . . : 28
    Período de vida . . . : 49
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2600:9000:2548:a800:16:b14c:cc40:93a1


    Nombre de registro  . : firefoxusercontent.com
    Tipo de registro  . . : 28
    Período de vida . . . : 49
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2600:9000:2548:1800:16:b14c:cc40:93a1


    Nombre de registro  . : firefoxusercontent.com
    Tipo de registro  . . : 28
    Período de vida . . . : 49
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2600:9000:2548:9e00:16:b14c:cc40:93a1


    Nombre de registro  . : firefoxusercontent.com
    Tipo de registro  . . : 28
    Período de vida . . . : 49
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2600:9000:2548:ce00:16:b14c:cc40:93a1


    Nombre de registro  . : firefoxusercontent.com
    Tipo de registro  . . : 28
    Período de vida . . . : 49
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2600:9000:2548:5800:16:b14c:cc40:93a1


    Nombre de registro  . : firefoxusercontent.com
    Tipo de registro  . . : 28
    Período de vida . . . : 49
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2600:9000:2548:9a00:16:b14c:cc40:93a1


    Nombre de registro  . : firefoxusercontent.com
    Tipo de registro  . . : 28
    Período de vida . . . : 49
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2600:9000:2548:b400:16:b14c:cc40:93a1


    Nombre de registro  . : firefoxusercontent.com
    Tipo de registro  . . : 28
    Período de vida . . . : 49
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2600:9000:2548:f800:16:b14c:cc40:93a1


    firefoxusercontent.com
    ----------------------------------------
    Nombre de registro  . : firefoxusercontent.com
    Tipo de registro  . . : 1
    Período de vida . . . : 48
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 18.238.171.84


    Nombre de registro  . : firefoxusercontent.com
    Tipo de registro  . . : 1
    Período de vida . . . : 48
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 18.238.171.35


    Nombre de registro  . : firefoxusercontent.com
    Tipo de registro  . . : 1
    Período de vida . . . : 48
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 18.238.171.74


    Nombre de registro  . : firefoxusercontent.com
    Tipo de registro  . . : 1
    Período de vida . . . : 48
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 18.238.171.65


    shepherd.ff.avast.com
    ----------------------------------------
    Nombre de registro  . : shepherd.ff.avast.com
    Tipo de registro  . . : 5
    Período de vida . . . : 67
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : shepherd-gcp.ff.avast.com


    Nombre de registro  . : shepherd-gcp.ff.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 67
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.160.176.28


    continuum.dds.microsoft.com
    ----------------------------------------
    Nombre de registro  . : continuum.dds.microsoft.com
    Tipo de registro  . . : 5
    Período de vida . . . : 263
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : cs-geo-dds.trafficmanager.net


    Nombre de registro  . : cs-geo-dds.trafficmanager.net
    Tipo de registro  . . : 1
    Período de vida . . . : 263
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 20.190.4.251


    fp2e7a.wpc.phicdn.net
    ----------------------------------------
    Nombre de registro  . : fp2e7a.wpc.phicdn.net
    Tipo de registro  . . : 1
    Período de vida . . . : 985
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 192.229.211.108


    profile.accounts.firefox.com
    ----------------------------------------
    Nombre de registro  . : profile.accounts.firefox.com
    Tipo de registro  . . : 1
    Período de vida . . . : 37
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 52.41.128.201


    Nombre de registro  . : profile.accounts.firefox.com
    Tipo de registro  . . : 1
    Período de vida . . . : 37
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 52.42.197.22


    Nombre de registro  . : profile.accounts.firefox.com
    Tipo de registro  . . : 1
    Período de vida . . . : 37
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 35.160.159.48


    Nombre de registro  . : profile.accounts.firefox.com
    Tipo de registro  . . : 1
    Período de vida . . . : 37
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 54.188.106.72


    Nombre de registro  . : profile.accounts.firefox.com
    Tipo de registro  . . : 1
    Período de vida . . . : 37
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 52.26.228.251


    Nombre de registro  . : profile.accounts.firefox.com
    Tipo de registro  . . : 1
    Período de vida . . . : 37
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 52.43.249.83


    r3.o.lencr.org
    ----------------------------------------
    Nombre de registro  . : r3.o.lencr.org
    Tipo de registro  . . : 5
    Período de vida . . . : 10
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : o.lencr.edgesuite.net


    Nombre de registro  . : o.lencr.edgesuite.net
    Tipo de registro  . . : 5
    Período de vida . . . : 10
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : a1887.dscq.akamai.net


    Nombre de registro  . : a1887.dscq.akamai.net
    Tipo de registro  . . : 1
    Período de vida . . . : 10
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 104.124.0.8


    Nombre de registro  . : a1887.dscq.akamai.net
    Tipo de registro  . . : 1
    Período de vida . . . : 10
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 23.193.172.216


    login.live.com
    ----------------------------------------
    Nombre de registro  . : login.live.com
    Tipo de registro  . . : 5
    Período de vida . . . : 12
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : login.msa.msidentity.com


    Nombre de registro  . : login.msa.msidentity.com
    Tipo de registro  . . : 5
    Período de vida . . . : 12
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : www.tm.lg.prod.aadmsa.trafficmanager.net


    Nombre de registro  . : www.tm.lg.prod.aadmsa.trafficmanager.net
    Tipo de registro  . . : 5
    Período de vida . . . : 12
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : prda.aadg.msidentity.com


    Nombre de registro  . : prda.aadg.msidentity.com
    Tipo de registro  . . : 5
    Período de vida . . . : 12
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : www.tm.a.prd.aadg.trafficmanager.net


    Nombre de registro  . : www.tm.a.prd.aadg.trafficmanager.net
    Tipo de registro  . . : 1
    Período de vida . . . : 12
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 20.190.155.130


    Nombre de registro  . : www.tm.a.prd.aadg.trafficmanager.net
    Tipo de registro  . . : 1
    Período de vida . . . : 12
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 20.190.155.131


    Nombre de registro  . : www.tm.a.prd.aadg.trafficmanager.net
    Tipo de registro  . . : 1
    Período de vida . . . : 12
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 20.190.155.65


    Nombre de registro  . : www.tm.a.prd.aadg.trafficmanager.net
    Tipo de registro  . . : 1
    Período de vida . . . : 12
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 20.190.155.1


    Nombre de registro  . : www.tm.a.prd.aadg.trafficmanager.net
    Tipo de registro  . . : 1
    Período de vida . . . : 12
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 20.190.155.2


    Nombre de registro  . : www.tm.a.prd.aadg.trafficmanager.net
    Tipo de registro  . . : 1
    Período de vida . . . : 12
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 20.190.155.67


    Nombre de registro  . : www.tm.a.prd.aadg.trafficmanager.net
    Tipo de registro  . . : 1
    Período de vida . . . : 12
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 20.190.155.16


    Nombre de registro  . : www.tm.a.prd.aadg.trafficmanager.net
    Tipo de registro  . . : 1
    Período de vida . . . : 12
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 20.190.155.66


    contile.services.mozilla.com
    ----------------------------------------
    Nombre de registro  . : contile.services.mozilla.com
    Tipo de registro  . . : 1
    Período de vida . . . : 124
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.117.237.239


    aus5.mozilla.org
    ----------------------------------------
    Nombre de registro  . : aus5.mozilla.org
    Tipo de registro  . . : 5
    Período de vida . . . : 15
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : balrog-aus5.r53-2.services.mozilla.com


    Nombre de registro  . : balrog-aus5.r53-2.services.mozilla.com
    Tipo de registro  . . : 5
    Período de vida . . . : 15
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : prod.balrog.prod.cloudops.mozgcp.net


    Nombre de registro  . : prod.balrog.prod.cloudops.mozgcp.net
    Tipo de registro  . . : 1
    Período de vida . . . : 15
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 35.244.181.201


    ocsp.pki.goog
    ----------------------------------------
    Nombre de registro  . : ocsp.pki.goog
    Tipo de registro  . . : 5
    Período de vida . . . : 62
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : pki-goog.l.google.com


    Nombre de registro  . : pki-goog.l.google.com
    Tipo de registro  . . : 28
    Período de vida . . . : 62
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2607:f8b0:4012:81b::2003


    ocsp.pki.goog
    ----------------------------------------
    Nombre de registro  . : ocsp.pki.goog
    Tipo de registro  . . : 5
    Período de vida . . . : 42
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : pki-goog.l.google.com


    Nombre de registro  . : pki-goog.l.google.com
    Tipo de registro  . . : 1
    Período de vida . . . : 42
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 142.251.35.3


    pki-goog.l.google.com
    ----------------------------------------
    Nombre de registro  . : pki-goog.l.google.com
    Tipo de registro  . . : 28
    Período de vida . . . : 79
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2607:f8b0:4012:81b::2003


    pki-goog.l.google.com
    ----------------------------------------
    Nombre de registro  . : pki-goog.l.google.com
    Tipo de registro  . . : 1
    Período de vida . . . : 42
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 142.251.35.3


    analytics.ff.avast.com
    ----------------------------------------
    Nombre de registro  . : analytics.ff.avast.com
    Tipo de registro  . . : 5
    Período de vida . . . : 456
    Longitud de datos . . : 8
    Sección . . . . . . . : respuesta
    Registro CNAME. . . . : analytics-prod-gcp.ff.avast.com


    Nombre de registro  . : analytics-prod-gcp.ff.avast.com
    Tipo de registro  . . : 1
    Período de vida . . . : 456
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.117.223.223


    config.nos.avast.com
    ----------------------------------------
    Nombre de registro  . : config.nos.avast.com
    Tipo de registro  . . : 16
    Período de vida . . . : 2766
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    prod.content-signature-chains.prod.webservices.mozgcp.net
    ----------------------------------------
    Nombre de registro  . : prod.content-signature-chains.prod.webservices.mozgcp.net
    Tipo de registro  . . : 28
    Período de vida . . . : 260
    Longitud de datos . . : 16
    Sección . . . . . . . : respuesta
    Registro AAAA . . . . : 2600:1901:0:92a9::


    prod.content-signature-chains.prod.webservices.mozgcp.net
    ----------------------------------------
    Nombre de registro  . : prod.content-signature-chains.prod.webservices.mozgcp.net
    Tipo de registro  . . : 1
    Período de vida . . . : 202
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.160.144.191


    prod.detectportal.prod.cloudops.mozgcp.net
    ----------------------------------------
    Nombre de registro  . : prod.detectportal.prod.cloudops.mozgcp.net
    Tipo de registro  . . : 1
    Período de vida . . . : 513
    Longitud de datos . . : 4
    Sección . . . . . . . : respuesta
    Un registro (host). . : 34.107.221.82

