{
    "name": "Cloud Shell",
    "short_name": "Cloud Shell",
    "background_color": "#FFFFFF",
    "display": "standalone",
    "start_url": "/",
    "scope": "/",
    "icons": [
        {
            "src": "https://www.gstatic.com/cloudssh/images/favicon-24-4efde84837951fea412b4bcb7287414f.png",
            "sizes": "24x24",
            "type": "image/png"
        },
        {
            "src": "https://www.gstatic.com/cloudssh/images/favicon-32-dc34aa1a696e06bb830614570e4abbfa.png",
            "sizes": "32x32",
            "type": "image/png"
        },
        {
            "src": "https://www.gstatic.com/cloudssh/images/favicon-36-1913429df613268b52315e1ef83566b4.png",
            "sizes": "36x36",
            "type": "image/png"
        },
        {
            "src": "https://www.gstatic.com/cloudssh/images/favicon-48-e4555bcfcf51cb920ac602b69c33db0f.png",
            "sizes": "48x48",
            "type": "image/png"
        },
        {
            "src": "https://www.gstatic.com/cloudssh/images/favicon-64-9bb671ac4329f656283d5a25ef14c249.png",
            "sizes": "64x64",
            "type": "image/png"
        },
        {
            "src": "https://www.gstatic.com/cloudssh/images/favicon-72-57973251c1e56eecad813f308e0f5980.png",
            "sizes": "72x72",
            "type": "image/png"
        },
        {
            "src": "https://www.gstatic.com/cloudssh/images/favicon-96-5038da59e38d89c5d38cba5079671928.png",
            "sizes": "96x96",
            "type": "image/png"
        },
        {
            "src": "https://www.gstatic.com/cloudssh/images/favicon-128-b0721b3b2668b2392ea994a73954627a.png",
            "sizes": "128x128",
            "type": "image/png"
        },
        {
            "src": "https://www.gstatic.com/cloudssh/images/favicon-192-5bf59255b7c44caaae3120868153fed9.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "https://www.gstatic.com/cloudssh/images/favicon-512-1cb190411173842341563db527071a34.png",
            "sizes": "512x512",
            "type": "image/png"
        }
    ],
    "orientation": "any",
    "related_applications": [],
    "shortcuts": []
}
